[package]
name = "init_driver"
version = "0.1.0"
edition = "2021"

[dependencies]
ungeckit = {path = "../../"}
serde_json = "1.0.125"
simplelog = "0.12.2"
tokio = { version = "1.39.2", features = ["full"] }
fake_user_agent = "0.2.1"
